name: mealmateapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  share_plus: ^9.0.0
  image_picker: ^1.1.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  sensors_plus: ^5.0.1
  url_launcher: ^6.3.0 # Ensure this is present

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true