// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZRvWVH8VYluOMaWiVCepyizvKO_tWp0',
    appId: '1:903986789534:android:79855a399150d137df4f8f',
    messagingSenderId: '903986789534',
    projectId: 'recipeapp-ac2f3',
    storageBucket: 'recipeapp-ac2f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwfRngtEI8FvvBdasH6zfL3FWgsiEAwA',
    appId: '1:903986789534:ios:b65aae4ff17ccd11df4f8f',
    messagingSenderId: '903986789534',
    projectId: 'recipeapp-ac2f3',
    storageBucket: 'recipeapp-ac2f3.firebasestorage.app',
    iosBundleId: 'com.example.mealmateapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZRvWVH8VYluOMaWiVCepyizvKO_tWp0', // Use the API key you provided
    appId: '1:903986789534:web:584f512388d9d943df4f8f', // Already correct
    messagingSenderId: '903986789534', // Already correct
    projectId: 'recipeapp-ac2f3', // Already correct
    authDomain: 'recipeapp-ac2f3.firebaseapp.com', // Already correct
    storageBucket: 'recipeapp-ac2f3.firebasestorage.app', // Already correct
    measurementId: 'G-3REZ2RVFBJ', // Already correct
    databaseURL: 'https://recipeapp-ac2f3-default-rtdb.firebaseio.com', // Add this line
  );
}